"""Add updated_at to APIKey model

Revision ID: 5f0c61c8a99f
Revises: f0b0c3634af8
Create Date: 2025-06-26 09:56:07.964318

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5f0c61c8a99f'
down_revision = 'f0b0c3634af8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('api_keys', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('api_keys', schema=None) as batch_op:
        batch_op.drop_column('updated_at')

    # ### end Alembic commands ###
