"""Add context_window to ConfiguredModel

Revision ID: b69f1f458606
Revises: 5f0c61c8a99f
Create Date: 2025-06-26 09:59:57.075951

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b69f1f458606'
down_revision = '5f0c61c8a99f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('configured_models', schema=None) as batch_op:
        batch_op.add_column(sa.Column('context_window', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('configured_models', schema=None) as batch_op:
        batch_op.drop_column('context_window')

    # ### end Alembic commands ###
